name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Wait for app to be ready
        run: |
          echo "Waiting for application to start..."
          sleep 10

      - name: Show current folder
        run: ls -la

      - name: Install dependencies
        working-directory: ./TestFrameworkNB
        run: mvn clean install -DskipTests

      - name: Run RestAssured and UI tests using TestNG
        working-directory: ./TestFrameworkNB
        run: mvn test
        env:
          HEADLESS: "true"

      - name: Generate Allure Report
        working-directory: ./TestFrameworkNB
        run: mvn allure:report
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.KANBAN_TOKEN }}
          publish_dir: ./TestFrameworkNB/target/site/allure-maven-plugin/
          destination_dir: allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: ./TestFrameworkNB/target/site/allure-maven-plugin/
          retention-days: 7