name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright/java:v1.46.0-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Show current folder
        run: ls -la

      - name: Open tests folder
        working-directory: /home/runner/work/kanban-board/kanban-board/e2e-tests
        run: ls -la

#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'

      - name: Build & Install
        working-directory: /home/runner/work/kanban-board/kanban-board/e2e-tests
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: Ensure browsers are installed
        working-directory: /home/runner/work/kanban-board/kanban-board/e2e-tests
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Run tests
        working-directory: /home/runner/work/kanban-board/kanban-board/e2e-tests
        run: mvn compile exec:java -D exec.mainClass="com.myakushev.App"